### ISSUE TITLE
TSO plugin has issue not handling "NA"

### ISSUE THREAD

**Issue by aledj2** [moka-guys/multiqc_plugins#12]
self.tso500_data_samples[sample][metric] = float(data[i])                │
│ ValueError: could not convert string to float: 'NA'      

project-GKYbqYj0FvQ2GQV2PFbb1Y2B:job-GKZ4gg80FvQ1zYk6FkbqF5b6

**Comment by aledj2** [comment]
This line https://github.com/moka-guys/multiqc_plugins/blob/ba3d2437cdc488c897aa3abfaf162700e6568aad/seglh_plugin/modules/tso500/tso500.py#L280
should be updated like  https://github.com/moka-guys/multiqc_plugins/blob/ba3d2437cdc488c897aa3abfaf162700e6568aad/seglh_plugin/modules/tso500/tso500.py#L269

**Comment by RachelDuffin** [comment]
This was fixed in v1.2.0
