### ISSUE TITLE
somp.py - when creating the samplename it removes .varscan or .vardict from the samplename. 

### ISSUE THREAD

**Issue by aledj2** [moka-guys/multiqc_plugins#6]
This means that if run for swift, if we run HD200 through both callers only one will appear on the report.
We could take this into account in the sompy app (not yet developed)

**Comment by aledj2** [comment]
https://github.com/moka-guys/multiqc_plugins/blob/ba3d2437cdc488c897aa3abfaf162700e6568aad/seglh_plugin/modules/sompy/sompy.py#L230

**Comment by rebeccahaines1** [comment]
This is fixed in PR#10
